name: space-nerds-in-space
base: core24
version: 1.0.9
platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  arm64:
    build-on: [arm64]
    build-for: [arm64]
summary: Spaceship bridge simulator
description: |
 Space Nerds In Space is an open source (GPLv2) cooperative multiplayer starship simulator for linux.
 So go out and get together with a crew of your linux-nerd friends and their computers in a room with a projector or TV, and go forth and explore the galaxy. 
grade: stable
confinement: strict
icon: io.github.smcameron.space-nerds-in-space.svg

apps:
  space-nerds-in-space:
    command-chain: [desktop-launch-space-nerds-in-space]
    command: usr/bin/snis_client --fullscreen --auto-download-assets
    desktop: usr/share/applications/io.github.smcameron.space-nerds-in-space.desktop 
    common-id: io.github.smcameron.space-nerds-in-space
    extensions: [kde-neon-6]
    plugs: &plugs
      - joystick
      - screen-inhibit-control
  launcher:
    command-chain: [desktop-launch-space-nerds-in-space]
    command: usr/bin/snis_launcher
    extensions: [kde-neon-6]
    plugs: *plugs

plugs:
  shared-memory:
    private: true

layout:
  /usr/bin/lsssgl:
    symlink: $SNAP/usr/bin/lsssgl
  /usr/bin/snis_arduino:
    symlink: $SNAP/usr/bin/snis_arduino
  /usr/bin/snis_client:
    symlink: $SNAP/usr/bin/snis_client
  /usr/bin/snis_launcher:
    symlink: $SNAP/usr/bin/snis_launcher
  /usr/bin/snis_multiverse:
    symlink: $SNAP/usr/bin/snis_multiverse
  /usr/bin/snis_server:
    symlink: $SNAP/usr/bin/snis_server
  /usr/bin/snis_text_to_speech.sh:
    symlink: $SNAP/usr/bin/snis_text_to_speech.sh
  /usr/bin/snis_update_assets:
    symlink: $SNAP/usr/bin/snis_update_assets
  /usr/bin/ssgl_server:
    symlink: $SNAP/usr/bin/ssgl_server
  /usr/bin/update_assets_from_launcher.sh:
    symlink: $SNAP/usr/bin/update_assets_from_launcher.sh
  /usr/share/snis:
    symlink: $SNAP/usr/share/snis
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/alsa-lib:
    symlink: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/alsa-lib

parts:
  space-nerds-in-space-app:
    plugin: make
    source: https://github.com/smcameron/space-nerds-in-space.git
    source-tag: v$SNAPCRAFT_PROJECT_VERSION
    make-parameters:
      - PREFIX=/usr
      - WITHVOICECHAT=yes
    build-packages:
      - build-essential
      - portaudio19-dev
      - libpng-dev
      - libvorbis-dev
      - libsdl2-dev
      - libsdl2-2.0-0
      - liblua5.2-dev
      - libglew-dev
      - libttspico-utils
      - sox
      - libcrypt-dev
      - libcurl4-openssl-dev
      - libssl-dev
      - libopus-dev 
      - libopus0

  dependencies:
    after: [space-nerds-in-space-app]
    plugin: nil
    stage-packages:
      - libsdl2-2.0-0
      - libdecor-0-0
      - libjack-jackd2-0
      - libportaudio2
      - libasound2t64
      - libasound2-plugins
      - libttspico-utils
      - espeak

  cleanup:
    after: [space-nerds-in-space-app, dependencies]
    plugin: nil
    build-snaps:
      - mesa-2404
      - kf6-core24
    override-prime: |
      set -eux
      cd /snap/mesa-2404/current/usr/lib
      find . -type f,l -exec rm -f $CRAFT_PRIME/usr/lib/{} \;
      cd /snap/mesa-2404/current/usr/share
      find . -type f,l -exec rm -f $CRAFT_PRIME/usr/share/{} \;

      cd /snap/kf6-core24/current/usr/lib
      find . -type f,l -exec rm -f $CRAFT_PRIME/usr/lib/{} \;
      cd /snap/kf6-core24/current/usr/share
      find . -type f,l -exec rm -f $CRAFT_PRIME/usr/share/{} \;

  command-chain:
    after: [cleanup]
    plugin: dump
    source: ./command-chain/
    override-build: |
      craftctl default
      chmod +x desktop-launch-space-nerds-in-space
